name: flutter_loadmore_drhoang999
description: listview scroll to bottom ,can load more data. help developer paging load data.
version: 1.0.4
email: drhoang999@gmail.com
homepage: https://github.com/drhoang999/flutter_loadmore_drhoang999

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.3.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
